namespace ArbScanner.Learning;

/// <summary>One term: what it means, how it should change what you do, and a worked example.</summary>
public record GlossaryEntry(string Id, string Term, string Meaning, string HowItAffectsYou, string Example);

/// <summary>Every term the app uses. ⓘ buttons reference entries by <see cref="GlossaryEntry.Id"/>.</summary>
public static class Glossary
{
    public static readonly IReadOnlyList<GlossaryEntry> Entries = new List<GlossaryEntry>
    {
        new("arbitrage", "Arbitrage",
            "Buying both sides of the same yes/no question on two different exchanges for less than $1 total. Exactly one side pays $1 when the question is settled, so the difference is profit no matter what happens.",
            "It's only 'risk-free' if both exchanges are really asking the same question and settle it the same way. Your job is to check that; the math is the easy part.",
            "Kalshi sells YES at 45¢ and Polymarket US sells NO at 52¢. You pay 97¢ for one of each. Whatever happens, one pays $1, so you make 3¢ before fees."),
        new("yes-no", "YES and NO",
            "Every market is a yes/no question. A YES contract pays $1 if the answer is yes; a NO contract pays $1 if it's no. Prices are in cents and act like probabilities: YES at 30¢ means the market thinks ~30% likely.",
            "On one exchange YES + NO always costs about $1 (plus a small spread). An arb appears only when you mix exchanges: one exchange's YES with the other's NO.",
            "'Will the Chiefs win?' YES 62¢ / NO 39¢ on Kalshi. If the Chiefs win, YES holders get $1 each and NO holders get nothing."),
        new("contract", "Contract",
            "One share of a YES or NO side. It pays exactly $1 if it wins and $0 if it loses.",
            "Opportunity sizes are in contracts. 300 contracts on each side means one side will pay $300.",
            "Buying 300 YES at 45¢ costs $135. If YES wins you get $300."),
        new("ask-bid", "Ask and bid",
            "The ask is the cheapest price someone will sell to you right now; the bid is the highest someone will pay you. Buying 'now' means paying the ask.",
            "All the math in this app uses asks, because that's what you'd really pay. Prices you see on a market's home page (last trade, midpoint) can make an arb look better than it is.",
            "Bid 44¢ / Ask 46¢: buying right now costs 46¢, not 45¢."),
        new("order-book", "Order book and depth",
            "The list of every waiting order at each price. Depth is how many contracts are available at a price before you have to pay more.",
            "If only 40 contracts sit at the best price, buying 300 means paying worse prices for the other 260. The scanner walks the book and averages this in, but thin books also mean the price can vanish before you act.",
            "Kalshi YES asks: 45¢ × 40, 46¢ × 200, 48¢ × 1,000. Buying 300 costs 40×45 + 200×46 + 60×48 = $138.80 (46.3¢ average)."),
        new("edge", "Edge (¢ per contract)",
            "How much profit each pair of contracts makes after fees: $1 minus what you paid for both sides minus fees. This is the main 'how good is it' number.",
            "Under about 2¢ is fragile: a 1–2¢ price move on either exchange before you finish both orders wipes it out. 3¢+ gives you breathing room. Your 'Min edge' setting hides anything below your bar.",
            "YES 45¢ + NO 52¢ = 97¢, fees ≈ 3.5¢ → edge = 100 − 97 − 3.5 = −0.5¢ (a loss). At 44¢ + 51¢ the edge is about +1.5¢."),
        new("fees", "Fees",
            "Both exchanges charge buyers a fee that's largest for 50¢ contracts and shrinks near 0¢ or 100¢. Kalshi: 7% × price × (1 − price) per contract, rounded up to the cent. Polymarket US: 6.95% × price × (1 − price).",
            "Fees often decide whether an arb is real. Two 50¢ sides cost about 3.5¢ in fees together, so you need a gap bigger than that. Lopsided prices (e.g. 90¢ / 8¢) have much smaller fees.",
            "100 contracts at 50¢ on Kalshi: 0.07 × 100 × 0.5 × 0.5 = $1.75 fee."),
        new("profit", "Profit",
            "The dollars you lock in on the whole opportunity: contracts × $1 − everything you paid (both sides plus fees).",
            "Small profits aren't worth the effort and risk of placing two orders. 'Min profit' filters these out.",
            "300 contracts at a 1.7¢ edge = $5.10 profit."),
        new("roi", "Return (ROI)",
            "Profit divided by the money you spent. It tells you how hard your cash is working on this one trade.",
            "A 2% return sounds small, but it's nearly guaranteed. Compare it with how long your money is stuck (see annualized return).",
            "Spend $294.90, get $300 back → $5.10 profit = 1.7% return."),
        new("annualized", "Annualized return",
            "The return scaled to a full year, based on how long until the markets settle. It answers: 'If I kept doing trades like this all year, what would I earn?'",
            "This is the fairest way to compare arbs. 2% that settles tomorrow is excellent (hundreds of % a year); 2% that settles in 10 months is worse than a savings account. Use 'Min annualized' to hide slow ones.",
            "1.7% in 6 days ≈ 103%/yr. The same 1.7% over 300 days ≈ 2%/yr."),
        new("lockup", "Capital lock-up",
            "Your money is stuck in both positions until the markets settle. You can sell early, but that usually gives back the edge.",
            "Long lock-ups tie up cash you could use on better arbs. Prefer opportunities that settle soon, unless the edge is big.",
            "A season-long market (settles in February) locks $500 for months to earn maybe $8."),
        new("deal-rating", "Deal rating (1–10)",
            "One number for how good a pair or opportunity is. It multiplies two things: confidence that both exchanges are asking the same question (match quality, Same vs Inverse, dates, rule-sensitive market types, suspicious gaps) and the profit per contract after fees.",
            "Sort and filter by it to spend your time on the best pairs. 9–10: every check passed and there's real profit, so look now. 5–8: worth reviewing. 1–4: usually skip. A 10 is not 'can't lose': two exchanges can still settle the same question differently, so read the rules first. Review ratings use prices from the last scan (up to 30 min old); the scanner re-checks live order books before calling anything an opportunity.",
            "100/100 name match, same 47.5 line, 6¢ after fees → 10. Perfect match but 4¢ short of a gap → 3. A 40¢ 'gap' between look-alike markets → 3 or less, because a gap that big means they probably aren't the same bet."),
        new("match-score", "Match score",
            "How confident the matcher is that two markets are about the same thing (0–100), based on event names, outcome names, numbers and dates.",
            "100 means the wording lines up, not that the bets are identical. Even 100s can differ on overtime, cancellation or deadline rules. Always read the rules.",
            "'Chiefs vs Raiders: Over 45.5 points' vs 'KC Chiefs vs. LV Raiders | Over 45.5 total points' → 100."),
        new("gap", "Top-of-book gap",
            "What the two cheapest opposite sides cost right now, before fees. Under 100¢ means there's a visible gap.",
            "A small gap (1–8¢) on a well-matched pair is what you want to watch. A huge gap (20¢+) almost always means the markets aren't really the same question, so be more suspicious, not less.",
            "Kalshi YES 41¢ + Polymarket NO 55¢ = 96¢ → 4¢ gap before fees."),
        new("same-inverse", "Same vs Inverse",
            "Same: Kalshi YES and Polymarket YES are the same outcome. Inverse: Kalshi YES is Polymarket's NO, which happens when each exchange names a different side of the bet.",
            "Getting this wrong turns an arb into a double bet on one outcome. The app suggests one and explains why; confirm it by reading what each YES actually means.",
            "Polymarket's 'USC vs Penn State' game market: YES = USC, NO = Penn State. Kalshi's 'Penn State wins' YES is Polymarket's NO → Inverse."),
        new("head-to-head", "Head-to-head market",
            "Polymarket US often runs a whole game as one market: YES = the first team wins, NO = the second team wins. Kalshi usually has a separate market per team.",
            "When the Kalshi market is about the second team, the pair is Inverse.",
            "Polymarket 'Lakers vs Celtics': YES = Lakers, NO = Celtics. Kalshi 'Celtics win' YES ↔ Polymarket NO."),
        new("flipped-spread", "Flipped spread market",
            "Some Polymarket US spread markets are titled after the favorite ('USC wins by over 5.5') while their YES side is actually the underdog getting the points (Washington +5.5). So YES means the title does NOT happen.",
            "The matcher detects these and marks the pair Inverse. Double-check by looking at Polymarket's price: if YES is priced like the opposite of Kalshi's YES, it's flipped.",
            "Kalshi 'USC wins by over 5.5' YES ≈ 20¢; Polymarket's market with the same title has YES ≈ 84¢ → flipped, so Inverse."),
        new("rules", "Resolution rules",
            "The fine print that decides how a market settles: data source, deadline and time zone, whether overtime counts, what happens if the event is cancelled or postponed.",
            "This is where 'same' markets differ. If Kalshi counts overtime and Polymarket says 'regulation time', the pair can lose on both sides. When in doubt, reject.",
            "Soccer: Kalshi 'Arsenal wins' may include extra time in a cup; Polymarket 'Arsenal (Reg. Time)' only counts 90 minutes. A 2–2 draw then an extra-time win pays one but not the other."),
        new("divergent", "Divergent resolution",
            "When the two exchanges settle a pair differently, so both of your sides lose (or both win). The arb wasn't really an arb.",
            "One divergence can wipe out dozens of small wins. If you see any, look at why (rules difference? wrong Same/Inverse?) and be stricter approving similar pairs.",
            "Kalshi settles 'Team A' NO (game went to OT), Polymarket settles 'Team A (Reg. Time)' NO too. You held Kalshi NO + Polymarket YES and lost both sides."),
        new("leg-risk", "Leg risk",
            "Arbs need two separate orders, one per exchange. Between the first and second order, the second price can move or disappear.",
            "Place the side with less depth first, use limit orders at the shown prices, and skip edges smaller than a typical price move.",
            "You buy Kalshi YES at 45¢, but by the time you go to Polymarket the NO has moved from 52¢ to 56¢: now you're paying 101¢ plus fees."),
        new("paper", "Paper trading",
            "Simulated trades. When the scanner finds an opportunity it records what you would have bought at those exact prices, then tracks the result when the markets settle. No money moves.",
            "Use paper results to learn which kinds of pairs are really safe before risking money. A good track record across many settled pairs, with no divergences, is the signal you're looking for.",
            "Paper: 20 settled positions, +$43 total, 0 divergent → the matching is working for those market types."),
        new("settlement", "Settlement",
            "When the question is decided and each exchange pays $1 per winning contract. Sports usually settle within hours of the game; elections and season-long markets can take months.",
            "Settlement turns paper positions into real paper P&L, and it's where divergences show up.",
            "The game ends Sunday night; both exchanges settle Monday morning; the paper position shows its P&L."),
        new("min-edge", "Min edge (setting)",
            "The smallest profit per contract, after fees, that counts as an opportunity.",
            "Raise it to see fewer, safer alerts; lower it to see more marginal ones. 1–2¢ is aggressive; 3¢ is comfortable for manual trading.",
            "Min edge 2¢: an opportunity at 1.6¢/contract is ignored."),
        new("min-profit", "Min profit (setting)",
            "The smallest total dollar profit for the whole fillable size.",
            "It stops tiny-but-technically-profitable alerts (like 10 contracts at 2¢ = $0.20) from pinging you.",
            "Min profit $5: 300 contracts × 1.5¢ = $4.50 is ignored."),
        new("min-annualized", "Min annualized (setting)",
            "The smallest yearly-equivalent return. 0 turns the filter off.",
            "Set it to about 10–20% to skip slow futures where your money sits for months for a tiny gain.",
            "Min 15%: a 1% gain over 120 days (≈3%/yr) is ignored."),
        new("stake", "Paper stake cap (setting)",
            "The most the paper trader 'spends' (both sides together) on one opportunity. The scanner sizes each opportunity to fit under it.",
            "Set it to roughly what you'd really risk per trade, so paper results look like what you'd actually get.",
            "Cap $500: an opportunity with 2,000 contracts available is sized down to about 515."),
        new("cooldown", "Alert cooldown (setting)",
            "After an alert for a pair, the minutes before the app will alert for that pair again.",
            "Prices flicker in and out of an arb. The cooldown stops one pair from buzzing you every 30 seconds.",
            "Cooldown 30 min: an arb that reappears 10 minutes later doesn't send a second push."),
        new("quiet-hours", "Quiet hours (setting)",
            "Hours (server time, 0–23) when no notifications are sent. Opportunities and paper trades are still recorded.",
            "Use it so overnight West Coast games don't wake you. Check the Opps tab in the morning.",
            "Start 23, end 7: no pushes from 11 pm to 7 am."),
        new("match-settings", "Matching settings",
            "Min match score: how similar names must be for a pair to be suggested. Date window: how many days apart the two markets' dates can be.",
            "Higher score and a smaller window mean fewer, better suggestions. Lower values find more pairs but more junk to reject.",
            "Score 82 and window 7 days (defaults) gave about 5,500 suggestions on the first scan."),
    };

    static readonly Dictionary<string, GlossaryEntry> ById = Entries.ToDictionary(e => e.Id);

    public static GlossaryEntry? Find(string id) => ById.GetValueOrDefault(id);

    public static IEnumerable<GlossaryEntry> Search(string? query) =>
        string.IsNullOrWhiteSpace(query)
            ? Entries
            : Entries.Where(e => e.Term.Contains(query, StringComparison.OrdinalIgnoreCase)
                                 || e.Meaning.Contains(query, StringComparison.OrdinalIgnoreCase));
}
